In [102]:
# Importamos las librerías que necesitamos
# 
# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Configuraciones
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [103]:
# Leer el archivo CSV
df = pd.read_csv('HR RAW DATA.csv')
df.sample()

Unnamed: 0 Age Attrition BusinessTravel DailyRate Department  \
1474        1474  38        No            NaN    119,0$        NaN   

      DistanceFromHome  Education EducationField  employeecount  \
1474                 3          3  Life Sciences              1   

     employeenumber  EnvironmentSatisfaction  Gender HourlyRate  \
1474          307,0                        1       0         76   

      JobInvolvement  JobLevel            JobRole  JobSatisfaction  \
1474               3         3   SAleS EXeCuTive                 3   

     MaritalStatus MonthlyIncome  MonthlyRate  NUMCOMPANIESWORKED Over18  \
1474      Divorced           NaN         9647                   0      Y   

     OverTime  PercentSalaryHike PerformanceRating  RelationshipSatisfaction  \
1474      NaN                 12               3,0                         3   

     StandardHours  StockOptionLevel TOTALWORKINGYEARS  TrainingTimesLastYear  \
1474           NaN                 2               NaN                      6   

     WORKLIFEBALANCE  YearsAtCompany YearsInCurrentRole  \
1474             2,0              16                NaN   

      YearsSinceLastPromotion  YEARSWITHCURRMANAGER SameAsMonthlyIncome  \
1474                        5                    13                 NaN   

      DateBirth       Salary RoleDepartament  NUMBERCHILDREN RemoteWork  
1474       1985  1000000000$             NaN             NaN        Yes

Limpieza de las 13 primeras columnas del dataframe.

In [104]:
# Hago dos copias de seguridad y trabajo sobre  df1.

df1= df.copy()

# Me quedo solo con las primeras 13 columnas del dataframe.

df1.drop(columns=['JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'MonthlyRate',
       'NUMCOMPANIESWORKED', 'Over18', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TOTALWORKINGYEARS', 'TrainingTimesLastYear',
       'WORKLIFEBALANCE', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YEARSWITHCURRMANAGER',
       'SameAsMonthlyIncome', 'DateBirth', 'Salary', 'RoleDepartament',
       'NUMBERCHILDREN', 'RemoteWork'], axis=1, inplace=True)

df1.columns

Index(['Unnamed: 0', 'Age', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'employeecount', 'employeenumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate'],
      dtype='object')

### Renombro todas las columnas a minusculas

In [105]:

df1.columns = df1.columns.str.lower()
df1_copy = df1.copy() # Copia de seguridad antes de empezar a limpiar.

In [106]:
# COLUMNA AGE 

df1['age'].unique()

array(['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55',
       '40', '58', '35', '45', '33', '36', '34', 'forty-seven', '53',
       '43', '60', '32', '37', '49', '39', '50', '44', '30',
       'fifty-eight', '29', '31', '54', '57', '27', 'thirty-six', '28',
       '26', 'fifty-five', '25', 'fifty-two', 'thirty-one', '24',
       'thirty', '23', '22', '21', '20', 'twenty-six', '19',
       'thirty-seven', '18', 'thirty-two', 'twenty-four'], dtype=object)

In [107]:
mapeo_edades = {
'thirty-six': '36', 
'forty-seven': '47', 
'fifty-eight': '58', 
'thirty-six': '36', 
'fifty-five': '55', 
'fifty-two': '52', 
'thirty-one': '31',
'thirty': '30',
'twenty-six': '26',
'thirty-seven': '37', 
'thirty-two': '32', 
'twenty-four': '24'
}

# Cambio las edades escritas a mano 

df1['age'] = df1['age'].replace(mapeo_edades)
df1['age'].unique()


array(['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55',
       '40', '58', '35', '45', '33', '36', '34', '53', '43', '60', '32',
       '37', '49', '39', '50', '44', '30', '29', '31', '54', '57', '27',
       '28', '26', '25', '24', '23', '22', '21', '20', '19', '18'],
      dtype=object)

In [108]:
def pasar_a_float (cadena):
    try:
        return float(cadena)
    except: 
        return np.nar 
    
df1['age'] = df1['age'].apply(pasar_a_float)
df1['age'].dtype


dtype('float64')

In [109]:
df1['age']

0       51.0
1       52.0
2       42.0
3       47.0
4       46.0
        ... 
1609    36.0
1610    45.0
1611    39.0
1612    36.0
1613    46.0
Name: age, Length: 1614, dtype: float64

In [110]:
# COLUMNA BUSINESS TRAVEL. 

# Quitamos el travel de los nombres de los datos.

def quitar_travel (cadena):
    
    try:
        nueva_cadena = cadena.replace("travel_", "")
        return nueva_cadena
    except:
        return np.nan 

df1['businesstravel'] = df1['businesstravel'].apply(quitar_travel)

df1['businesstravel'].unique()

array([nan, 'rarely', 'frequently', 'non-travel'], dtype=object)

In [111]:
# COLUMNA DAILYRATE

# Eliminar $. Cambiar la (,) por (.). 

df1['dailyrate'] = df1['dailyrate'].apply(lambda x : x.replace(",", "." ).replace("$", ""))

df1['dailyrate']

0        684.0
1        699.0
2        532.0
3        359.0
4       1319.0
         ...  
1609     530.0
1610     805.0
1611     903.0
1612    1229.0
1613     566.0
Name: dailyrate, Length: 1614, dtype: object

In [112]:

df1['dailyrate'] = df1['dailyrate'].apply(pasar_a_float)
df1['dailyrate'].dtype

dtype('float64')

In [113]:
# COLUMNA DISTANCEFROMHOME

# Pasar a positivos los negativos

df1['distancefromhome'] = df1['distancefromhome'].apply(lambda x : abs(x))
df1['distancefromhome'].unique()

array([ 6,  1,  4,  2,  3, 22, 25,  9,  7, 23, 10, 12, 14, 13, 15,  8, 42,
       28, 37,  5, 16, 35, 26, 24, 29, 17, 21, 18, 30, 27, 20, 31, 39, 11,
       19, 33, 34, 46, 36, 45, 47, 32, 41, 49, 48, 38, 43, 40, 44])

In [114]:
# COLUMNA EMPLOYEECOUNT

# Eliminar 

df1.drop('employeecount', axis=1, inplace=True)

In [115]:
# Comprobamos que ha desaparecido
# 
df1.columns

Index(['unnamed: 0', 'age', 'attrition', 'businesstravel', 'dailyrate',
       'department', 'distancefromhome', 'education', 'educationfield',
       'employeenumber', 'environmentsatisfaction', 'gender', 'hourlyrate'],
      dtype='object')

In [116]:
df1['employeenumber'].unique()

array(['162,0', '259,0', '319,0', ..., '2012,0', '2023,0', '2040,0'],
      dtype=object)

In [117]:
# COLUMNA EMPLOYEENUMBER
# Reemplazar los valores faltantes por 'unknown'
# Quitar las comas y el decimal, pero dejarlo como string.

df1['employeenumber'] = df1['employeenumber'].fillna('unknown')
df1['employeenumber'] = df1['employeenumber'].apply(lambda x: (x.replace(",", ".")))

In [118]:
df1['employeenumber'].unique()

array(['162.0', '259.0', '319.0', ..., '2012.0', '2023.0', '2040.0'],
      dtype=object)

In [119]:
df1['environmentsatisfaction'].unique()

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])

In [120]:

# COLUMNA ENVIROMENTSATISFACTION

# Limpiar valores que no estén en escala 1 al 4 (Eliminar segunda cifra del número). Pasarlo a entero.

# df1['environmentsatisfaction'] = df1['environmentsatisfaction'].apply(lambda x: int(x))

def primera_cifra_int (numero):
    # Devuelve un entero que coincide con la primera cifra si la columna tiene más de un caracter
    cadena = str(numero)
    if len(cadena)>1: 
        return int(cadena[0])
    else: 
        return int(cadena)


In [121]:
df1['environmentsatisfaction'] = df1['environmentsatisfaction'].apply(primera_cifra_int)

In [122]:
df1['environmentsatisfaction'].unique()

array([1, 3, 4, 2])

In [123]:
df1['environmentsatisfaction'].dtype

dtype('int64')

In [124]:
df1['gender'].unique()

array([0, 1])

In [125]:
# COLUMNA GENDER

# Cambiar 0 a M. 1 a F. Cambiarlo a object

df1['gender'] = df1['gender'].map({0: 'M', 1: 'F'})
df1['gender']




0       M
1       M
2       M
3       F
4       F
       ..
1609    M
1610    M
1611    M
1612    M
1613    M
Name: gender, Length: 1614, dtype: object

In [126]:
df1['gender'].unique()

array(['M', 'F'], dtype=object)

In [127]:
# COLUMNA HOURLYRATE

# Limpiar registros que no tenga valor numerico a NaN( Ej: ‘not available’)Cambiarlo a tipo float.

df1['hourlyrate'] = df1['hourlyrate'].replace({'Not Available': '-1'})

def pasar_a_float (cadena):
    if cadena == '-1':
        return np.nan 
    else:
        return float(cadena)

df1['hourlyrate'] = df1['hourlyrate'].apply(pasar_a_float)


In [128]:
df1['hourlyrate'].unique()

array([ 51.,  65.,  58.,  82.,  45.,  99.,  91.,  64.,  55.,  68.,  49.,
        61.,  79.,  31.,  69.,  48.,  80.,  74.,  98.,  59.,  33.,  56.,
        66.,  57.,  53.,  87.,  81.,  84.,  32.,  41.,  92.,  47.,  nan,
        43.,  86.,  30.,  42.,  88.,  96.,  67.,  62.,  72.,  78.,  89.,
        52.,  50.,  90.,  37.,  94.,  76.,  60.,  46.,  83., 100.,  40.,
        97.,  54.,  75.,  39.,  85.,  63.,  44.,  93.,  36.,  35.,  73.,
        71.,  70.,  38.,  77.,  95.,  34.])

In [129]:
df1.head()

unnamed: 0   age attrition businesstravel  dailyrate  \
0           0  51.0        No            NaN      684.0   
1           1  52.0        No            NaN      699.0   
2           2  42.0        No         rarely      532.0   
3           3  47.0        No         rarely      359.0   
4           4  46.0        No            NaN     1319.0   

                 department  distancefromhome  education    educationfield  \
0                       NaN                 6          3               NaN   
1                       NaN                 1          4     Life Sciences   
2   Research & Development                  4          2  Technical Degree   
3                       NaN                 2          4           Medical   
4                       NaN                 3          3  Technical Degree   

  employeenumber  environmentsatisfaction gender  hourlyrate  
0          162.0                        1      M        51.0  
1          259.0                        3      M        65.0  
2          319.0                        3      M        58.0  
3        unknown                        1      F        82.0  
4        unknown                        1      F        45.0

In [130]:
df1.to_csv('columnas_ana_primera.csv')